---
title: "Homework 2: Community data"
author: "BSC 6926 B53"
date: "2022-10-25"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = T, cache = T)
```

## Instructions

Please, using RStudio and R, answer the questions below. You can use the class notes, the recommended books, and other web materials to help answer the questions. You can work on the homework in groups, but please independently send the R code and the answers to the short-essay questions.

**In two weeks (11/11/22)**, please submit your R code (R, text, or HTML file) and short answers (.doc file) to CANVAS using the following filename structure LastName_HW2_Filetype_Date (e.g., Santos_HW2_R_20221111). Again, you can share and work together on the code, but independently, submit your answers to the short essay questions in your own words. Please, add tables and figures for your answers in your doc file (i.e., do not refer me to the code). If you fill comfortable submitting a markdown or quarto showing both the code and results, the better (optional).

## Data for questions

For this homework, you will use one dataset. This dataset will be available in CANVAS under the HW2 link in the Modules tab and on the workshop website. This dataset is titled (LDWF2007seine.csv)[https://raw.githubusercontent.com/PCB5423/BSC6926_workshopScripts/master/data/LDWF2007seine.csv]. The dataset consists of nektonic species collected throughout the coastal marshes of Louisiana using seine nets. The sampling was performed monthly across distinct sampling basins (strata), and used to count all the individuals of species caught in the seine nets.  

## Questions

### Section 1 - Exploratory Analysis of the Community (20 pts)
1. Upload the LDWF seine data,filter for seines collected in the Calcasieu, Terrebonne, and Pontchartrain basin, and create a month column. (5pts) \
*-Hint: use the `lubridate` package and create a column for month based on the information in the date column (YYYYMMDD format)*

2. Identify the 15 most abundant species caught across these three basins based on the species' average abundance. (5 pts).

3. Calculate the average abundance of the top 15 species in each basin, and plot the average abundance for each species for each basin using a heat map (5 pts). 
*-Hint: `geom_raster()`.*

4. *Short essay question 1.1:* Based on the heatmaps, what can you conclude about the communities/assemblages across basins? (5 pts)

### Section 2 – Community assemblage dissimilarities (20 pts)
1. Calculate each species' monthly mean abundance per basin (3 pts).\

2. Convert the dataset from long format to wide format (2 pts).

3. Calculate the Bray Curtis dissimilarity and identify which points have the lowest and highest dissimilarity (5 pts).
*-Hint: Make a column that contains both the basin and the month to use as rownames of your matrix*

4. Project dissimilarity into 2-dimensional space using nonmetric multidimensional scaling and illustrate the results in a biplot (5 pts).

5. *Short essay question 2.1:* Based on the nMDS, what can you conclude about the communities/assemblages across basins? (5 pts)

## Section 3 - Characterize the species diversity of the nektonic community (15 pts)
1. Using the vegan package or a for loop, calculate the species richness, Simpson's evenness index, and Shannon index ($H$) per month for each basin (5 pts).

2. Plot each metric from question 1 for each month and basin (3 pts). 

3. *Short essay question 3.1:* Based on species richness, Simpson, and Shannon indices, what is happening to species diversity across basins and months? What can you tell about species evenness by looking at the plot? (7 pts).


